name: Cpp Tests

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc

      - name: Compile tests
        shell: msys2 {0}
        run: g++ -std=c++11 tests/test_minisearchx.cpp -o test_minisearchx.exe

      - name: Run tests
        shell: msys2 {0}
        run: ./test_minisearchx.exe